name: "Build and scan image on push to main branch"

on:
  push:
    branches: 
    - main
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions: write-all
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Run Trivy vulnerability scanner on docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: template
          #format: table
          template: '@/contrib/sarif.tpl'
          output: trivy-results-docker.sarif
          ignore-unfixed: true
          vuln-type: 'os'
          #vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          #exit-code: 1 # fail if there are any vulnerabilities

      - name: Upload Trivy scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: trivy-results-docker.sarif
